# Cramer's rule

The general idea being the parallelegrams (or higher dimensional parallelepipeds and such) formed by the basis vectors apart from (lets say) $x$ and the resultant vector, has unit base area and therefore it's area gives the transformed (in this case) $y$ component. Becuase we know the determinant of the tranformation (the factor by which the transformation scales the area of a shape - for example a parrelelagram), we can "undo" that scaling by dividing our parralelegram's area by the determinant. This gives us the original area of the parreleagram, which has the height of the y component of the original vector.

In [17]:
import numpy as np
from numpy.linalg import solve, det

array([2., 3.])

In [ ]:
A = np.array([[3, 1],
              [1, 3]])

b = np.array([9, 11])

In [42]:
def cramer(A, b):
  numer = det(A)
  b_col = b.reshape((2, 1))

  x_par = det(np.hstack((b_col, A[:,1].reshape((2, 1)))))
  x = x_par / numer

  y_par = det(np.hstack((A[:,0].reshape((2, 1)), b_col)))
  y = y_par / numer

  return np.array([x, y])


In [46]:
cramer(A, b), solve(A, b)

(array([2., 3.]), array([2., 3.]))

array([7, 1, 9])